language: node_js

node_js:
  - 10.15.0

cache:
  directories:
    - "node_modules"

notifications:
  email:
    on_success: never

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn lint
  - yarn build

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "dist"
  skip_cleanup: true
  on:
    tags: true
