language: node_js
node_js:
- 10.15.0
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never
install:
- yarn
script:
- yarn lint
- yarn build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: R3RChxrHM5uBqBZulyhq/XvBh0P6DHZR1hB9cM8whGv2Q9sSkd0ksFY2mspEKOuMuDkkPnsh0xJ6JmRBlWjetPDcjvDwRwVWl6VQ07K72in4DGwckYyOVP1c6r/w852F6wBB1wu2znnjfxILqKgHIBZGix6DF1CJmeOsiCz42E4940wft4GQUlr3kvGV7WVpzxWaebOYdpHNuLuTJtnF7pSnyaddC12ShbNYaO9jj8sDVBbCt2PUs+XejBoYQP/ErPu4Lj64o5rA1LkU2iVfkTQdkvQxdl+wkjeARdebmORMK81ds31o2fQZTJiImdlzylqjyDvUhDMR2dpR+jEuTd0Ih2XYirK7d+RZxu8OIS/Iq3+ZhyXK83DGFLH7vfIUmIHpHdiGDeI1yKbyVLjogvFxT5VOuv9oJHSsgiXndSQmqoJ2R2i1CDg+JnC993FgDwapQKWSXlnsTDNsYvZBaLIQKmy5h+VMXgPV5No2pAJ7FwclW6z0v0vr+jECAOF6jduZmYTpqykIESIUdgdFXB0FzagB2JAiI9nNKuQtXwILG3CH0ANTPwRLROqnSYaH2b0zn0CreewhobquFxrQwbrnMXyESaaUoLDoZZfPxMKWpGmuSHLk5Xqt5IzTZ4Wvbn12EImYzScZ7Uh7ft4tR9Tx/TLRu2/prW1i5Y568VU=
  file:
    - dist/index.js
    - dist/variables.env
  on:
    repo: HaiFengFE/via
    tags: true
